ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM0

USER_LIB_PATH = /home/pi/Line_follower/onArdu/Line_follower/libraries
# BOARD_TAG = mega2560
BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk
